package com.epgs.mail_notification;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class pk1 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public pk1() {
    }




}